import { createHash } from 'node:crypto';
import { DelegationRecords, type DelegationCheck, type DelegationSession, type DelegationSourceSnapshot, type DelegationTask, type DelegationVerification } from './delegation-records.js';
import { DelegationTasks } from './delegation-tasks.js';
import { Store } from './store.js';
import { now } from './runtime-status.js';
const text = (value: unknown, label: string, max = 500): string => { if (typeof value !== 'string' || !value || value.length > max || value.trim() !== value || Array.from(value).some(character => character.charCodeAt(0) < 32 || character.charCodeAt(0) === 127)) throw new Error(`${label} must be bounded nonempty text.`); return value; };
const argv = (value: unknown): string[] => { if (!Array.isArray(value) || !value.length || value.length > 100 || value.some(item => typeof item !== 'string' || !item || item.includes('\0')) || value.join('').length > 65_536) throw new Error('Verification command must be a bounded argv vector.'); return [...value]; };
const digest = (value: unknown): string => createHash('sha256').update(JSON.stringify(value)).digest('hex');

/** Durable command-check ledger; command execution remains owned by the scheduler. */
export class DelegationChecks {
  private readonly records: DelegationRecords;
  private readonly tasks: DelegationTasks;
  constructor(private readonly store: Store) { this.records = new DelegationRecords(store); this.tasks = new DelegationTasks(store); }
  private task(runId: string, taskId: string, attemptId: string): { task: DelegationTask; attempt: NonNullable<DelegationTask['attempts'][number]> } { const task = this.records.tasks(runId).find(item => item.id === taskId), attempt = task?.attempts.find(item => item.id === attemptId); if (!task || !attempt) throw new Error('Verification attempt does not exist.'); return { task, attempt }; }
  private save(task: DelegationTask): void { this.store.db.prepare('UPDATE delegation_tasks SET document=? WHERE id=?').run(JSON.stringify(task), task.id); }
  initialize(input: { runId: string; taskId: string; attemptId: string; expectedGeneration: number; commands: string[][]; source?: DelegationSourceSnapshot }): DelegationVerification {
    return this.store.transaction(() => {
      const task = this.tasks.assertRuntimeStage(input), attempt = task.attempts.find(item => item.id === input.attemptId)!;
      const authorization = this.records.authorizations(input.runId).find(item => item.id === task.authorizationId), plan = authorization && this.records.plans(input.runId).find(item => item.id === authorization.planId);
      if (plan?.plan.assignments.find(item => item.id === task.assignmentId)?.role !== 'runtime-verification') throw new Error('Only a runtime-verification assignment can initialize command checks.');
      if (!attempt.source) throw new Error('Verification requires a retained prepared input source.');
      if (input.source && JSON.stringify(input.source) !== JSON.stringify(attempt.source)) throw new Error('Verification input source does not match the prepared attempt source.');
      const commands = input.commands.map(argv); if (!commands.length || commands.length > 32 || new Set(commands.map(item => JSON.stringify(item))).size !== commands.length) throw new Error('Verification requires a bounded immutable command manifest.');
      const manifest = { input: attempt.source, commands: commands.map((item, index) => ({ id: `check-${index + 1}`, argv: item })) }, manifestDigest = digest(manifest);
      if (attempt.verification) { if (attempt.verification.manifestDigest !== manifestDigest) throw new Error('Verification manifest was already initialized differently.'); return attempt.verification; }
      const verification: DelegationVerification = { ...manifest, manifestDigest, checks: manifest.commands.map((command, index) => ({ ...command, sessionId: index === 0 ? text(attempt.sessionId, 'Primary verification session ID') : '', state: 'queued' })), createdAt: now(), updatedAt: now() };
      attempt.verification = verification; attempt.updatedAt = now(); this.save(task); const run = this.store.runs().find(item => item.id === input.runId)!; this.store.append(run, 'delegation.checks-initialized', 'Immutable runtime verification command manifest recorded.', { taskId: task.id, attemptId: attempt.id, manifestDigest }); return verification;
    });
  }
  claimNext(input: { runId: string; taskId: string; attemptId: string; expectedGeneration: number; checkId?: string; sessionId?: string }): { task: DelegationTask; check: DelegationCheck; session: DelegationSession } {
    return this.store.transaction(() => {
      const task = this.tasks.assertRuntimeStage(input), attempt = task.attempts.find(item => item.id === input.attemptId)!, verification = attempt.verification;
      if (!verification || verification.checks.some(check => check.state === 'cleanup-unconfirmed' || check.state === 'running' || check.state === 'dispatching') || verification.checks.some(check => check.state === 'failed' || check.state === 'interrupted' || check.state === 'unavailable')) throw new Error('Verification cannot claim another command.');
      const check = verification.checks.find(item => item.state === 'queued'); if (!check || (input.checkId && input.checkId !== check.id)) throw new Error('Verification claim must select the next queued command.');
      let session = check.sessionId ? this.records.sessions(input.runId).find(item => item.id === check.sessionId) : undefined;
      if (!session) { const primary = this.records.sessions(input.runId).find(item => item.id === attempt.sessionId); if (!primary || primary.role !== 'verification' || !input.sessionId || this.records.sessions(input.runId).some(item => item.id === input.sessionId)) throw new Error('Later verification checks require a new exact verification session ID.'); session = { ...primary, id: text(input.sessionId, 'Verification session ID'), admissionClaim: undefined, native: undefined, state: 'prepared', cleanupConfirmed: undefined, cleanupEvidence: undefined, error: undefined, createdAt: now(), updatedAt: now() }; check.sessionId = session.id; this.store.db.prepare('INSERT INTO delegation_sessions VALUES (?, ?, ?, ?)').run(session.id, session.runId, task.id, JSON.stringify(session)); }
      if (session.state !== 'prepared') throw new Error('Verification session is not prepared for command dispatch.'); session.cleanupConfirmed = undefined; session.cleanupEvidence = undefined; session.error = undefined; this.store.db.prepare('UPDATE delegation_sessions SET document=? WHERE id=?').run(JSON.stringify(session), session.id); check.state = 'dispatching'; verification.updatedAt = now(); attempt.updatedAt = now(); this.save(task); const run = this.store.runs().find(item => item.id === input.runId)!; this.store.append(run, 'delegation.check-claimed', 'Verification command claimed before native dispatch.', { taskId: task.id, attemptId: attempt.id, checkId: check.id, sessionId: session.id, argv: check.argv }); return { task, check, session };
    });
  }
  bindCommand(input: { runId: string; taskId: string; attemptId: string; checkId: string; sessionId: string; commandId: string; expectedGeneration: number }): DelegationCheck {
    return this.store.transaction(() => { this.tasks.assertRuntimeStage(input); const { task, attempt } = this.task(input.runId, input.taskId, input.attemptId), check = attempt.verification?.checks.find(item => item.id === input.checkId); if (!check || check.sessionId !== input.sessionId || check.state !== 'dispatching' || check.commandId) throw new Error('Verification command binding is stale.'); this.records.bindCommandSession({ runId: input.runId, sessionId: input.sessionId, commandId: input.commandId }); check.commandId = input.commandId; check.state = 'running'; attempt.verification!.updatedAt = now(); attempt.updatedAt = now(); this.save(task); return check; });
  }
  finishCheck(input: { runId: string; taskId: string; attemptId: string; checkId: string; sessionId: string; status: 'completed' | 'failed' | 'interrupted'; exitCode: number | null; output?: string; truncated?: boolean; observedTreeOid: string }): DelegationCheck {
    return this.store.transaction(() => { const { task, attempt } = this.task(input.runId, input.taskId, input.attemptId), check = attempt.verification?.checks.find(item => item.id === input.checkId), session = this.records.sessions(input.runId).find(item => item.id === input.sessionId); if (!check || !session || check.sessionId !== session.id || check.state !== 'running' || session.native?.commandId !== check.commandId) throw new Error('Verification result does not match its command session.'); const clean = session.cleanupConfirmed === true && session.state !== 'cleanup-unconfirmed'; if (input.status === 'completed' && (!clean || session.state !== 'completed' || input.exitCode !== 0)) throw new Error('A passed verification command requires completed native cleanup and exit code zero.'); check.exitCode = input.exitCode; check.output = typeof input.output === 'string' ? new TextDecoder().decode(Buffer.from(input.output).subarray(0, 16_384), { stream: true }) : undefined; check.truncated = input.truncated === true || (typeof input.output === 'string' && Buffer.byteLength(input.output) > 16_384); check.cleanupConfirmed = clean; check.cleanupEvidence = session.cleanupEvidence; check.observedTreeOid = text(input.observedTreeOid, 'Observed verification tree OID', 200); check.state = !clean ? 'cleanup-unconfirmed' : input.status === 'completed' && input.exitCode === 0 && check.observedTreeOid === attempt.verification!.input.treeOid ? 'passed' : input.status === 'interrupted' ? 'interrupted' : 'failed'; attempt.verification!.updatedAt = now(); attempt.updatedAt = now(); this.save(task); return check; });
  }
  deferCheck(input: { runId: string; taskId: string; attemptId: string; checkId: string; sessionId: string; cleanupEvidence?: Record<string, unknown> }): DelegationCheck {
    return this.store.transaction(() => { const { task, attempt } = this.task(input.runId, input.taskId, input.attemptId), check = attempt.verification?.checks.find(item => item.id === input.checkId), session = this.records.sessions(input.runId).find(item => item.id === input.sessionId); if (!check || !session || check.sessionId !== session.id || check.state !== 'dispatching' || session.native?.commandId || session.cleanupConfirmed !== true) throw new Error('Only a confirmed-cleanup undispatched check can be deferred.'); session.admissionClaim = undefined; session.state = 'prepared'; session.updatedAt = now(); check.state = 'queued'; attempt.verification!.updatedAt = now(); attempt.updatedAt = now(); this.store.db.prepare('UPDATE delegation_sessions SET document=? WHERE id=?').run(JSON.stringify(session), session.id); this.save(task); return check; });
  }
  failUndispatchedCheck(input: { runId: string; taskId: string; attemptId: string; checkId: string; sessionId: string; status: 'failed' | 'interrupted' | 'unavailable'; error: string }): DelegationCheck {
    return this.store.transaction(() => { const { task, attempt } = this.task(input.runId, input.taskId, input.attemptId), check = attempt.verification?.checks.find(item => item.id === input.checkId), session = this.records.sessions(input.runId).find(item => item.id === input.sessionId); if (!check || !session || check.sessionId !== session.id || check.state !== 'dispatching' || session.native?.commandId) throw new Error('Only an unbound claimed check can settle before dispatch.'); if (!['failed', 'interrupted', 'cleanup-unconfirmed'].includes(session.state)) throw new Error('Undispatched check settlement requires a terminal native cleanup receipt.'); check.state = session.cleanupConfirmed !== true ? 'cleanup-unconfirmed' : input.status; check.cleanupConfirmed = session.cleanupConfirmed; check.cleanupEvidence = session.cleanupEvidence; check.error = text(input.error, 'Check error', 1000); attempt.verification!.updatedAt = now(); attempt.updatedAt = now(); this.save(task); return check; });
  }
  reconcileOnReopen(): DelegationCheck[] { const changed: DelegationCheck[] = []; for (const run of this.store.runs()) this.store.transaction(() => { for (const task of this.records.tasks(run.id)) for (const attempt of task.attempts) for (const check of attempt.verification?.checks ?? []) if (['dispatching', 'running'].includes(check.state)) { const session = this.records.sessions(run.id).find(item => item.id === check.sessionId); if (session?.cleanupConfirmed && ['completed', 'failed', 'interrupted'].includes(session.state)) continue; check.state = 'cleanup-unconfirmed'; check.cleanupConfirmed = false; check.error = 'Application reopened before this verification check settled.'; attempt.verification!.updatedAt = now(); attempt.updatedAt = now(); this.save(task); changed.push(check); } }); return changed; }
  snapshot(input: { runId: string; taskId: string; attemptId: string }): DelegationVerification | undefined { return this.task(input.runId, input.taskId, input.attemptId).attempt.verification; }
  passed(input: { runId: string; taskId: string; attemptId: string }): boolean { const value = this.snapshot(input); return Boolean(value?.checks.length && value.checks.every(check => check.state === 'passed' && check.cleanupConfirmed && check.observedTreeOid === value.input.treeOid)); }
}
